### ISSUE TITLE
a problem about starting project

### ISSUE THREAD

**Issue by myhat123** [xiaohui-zhangxh/vue-webpack-cordova#1]
$ vue init xiaohui-zhangxh/vue-webpack-cordova my-project

module.js:471
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hzg/.vue-templates/xiaohui-zhangxh-vue-webpack-cordova/meta.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getMetadata (/usr/local/node-v6.9.5-linux-x64/lib/node_modules/vue-cli/lib/options.js:43:15)
    at options (/usr/local/node-v6.9.5-linux-x64/lib/node_modules/vue-cli/lib/options.js:15:14)
    at generate (/usr/local/node-v6.9.5-linux-x64/lib/node_modules/vue-cli/lib/generate.js:36:14)
    at /usr/local/node-v6.9.5-linux-x64/lib/node_modules/vue-cli/bin/vue-init:147:5

after installed shelljs, the problem is here yet. Why?

**Comment by myhat123** [comment]
It is OK after setting NODE_PATH

**Comment by xiaohui-zhangxh** [comment]
ok :)

**Comment by Faizan-Shakeel** [comment]
I have same error, cant initiate a project, could you please describe how to solve?

**Comment by xiaohui-zhangxh** [comment]
see #2, it's about your nvm doesn't set NODE_PATH correctly
