### ISSUE TITLE
Error: Cannot find module 'shelljs/global'

### ISSUE THREAD

**Issue by jjjachyty** [xiaohui-zhangxh/vue-webpack-cordova#3]
i have  npm install -g shelljs and success, but when i vue init xiaohui-zhangxh/vue-webpack-cordova rpm  the console out put :

module.js:457
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Janly/.vue-templates/xiaohui-zhangxh-vue-webpack-cordova/meta.js:1:63)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at getMetadata (/usr/local/lib/node_modules/vue-cli/lib/options.js:43:15)
    at options (/usr/local/lib/node_modules/vue-cli/lib/options.js:15:14)
    at generate (/usr/local/lib/node_modules/vue-cli/lib/generate.js:36:14)
    at /usr/local/lib/node_modules/vue-cli/bin/vue-init:147:5

**Comment by xiaohui-zhangxh** [comment]
see #2, it's about your nvm doesn't set NODE_PATH correctly, dup issue of #1 #2
